version: "3.9"
services:
    api-service:
        build: ./puma_server/
        ports: 
            - 5001:5001
        environment: 
            FLASK_APP: puma_app.py
            FLASK_RUN_PORT: 5001
            FLASK_DEBUG: 1
