version: "3.9"
services:
    api-service:
        build: ./puma-api/
        ports: 
            - 5000:5000
        environment: 
            FLASK_APP: app.py
            FLASK_RUN_PORT: 5000
            FLASK_DEBUG: 1
        volumes:
            - ./:api:/app
