FROM python:3.10.8

COPY requirements.txt /api/
RUN pip3 install -r /api/requirements.txt

WORKDIR /api
#COPY . .

ENV FLASK_APP=app
ENV FLASK_DEBUG=1
CMD  ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]